name: Cardinal Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install & build pskwebcomponents
      run: |
        cd ..
        git clone https://github.com/PrivateSky/pskwebcomponents.git
        cd pskwebcomponents
        npm ci
        echo $(npm run build)
    - name: npm install
      run: |
        npm ci
        gulp build
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.CARDINAL }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: release # The folder the action should deploy.
        CLEAN: true   
